# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' create_sin_cos
#'
#' fit sin curves to atv data
#'
#' @param n_rows the number of rows in the atv image
#' @param n_curves the number of sin/cos curves to use
#'
#' @return fitting coefficients
#'
#' @useDynLib atv
#' @importFrom Rcpp evalCpp
#' @importFrom RcppParallel RcppParallelLibs
#'
#' @export
#'
create_sin_cos <- function(n_rows, n_curves) {
    .Call('atv_create_sin_cos', PACKAGE = 'atv', n_rows, n_curves)
}

#' sin_fit_ols_parallel
#'
#' fit sin curves to atv data.
#'
#' @param y atv matrix of data
#' @param n_curves the number of sin/cos curves to use
#'
#' @return fitting coefficients
#'
#' @export
#'
sin_fit_ols_parallel <- function(y, n_curves) {
    .Call('atv_sin_fit_ols_parallel', PACKAGE = 'atv', y, n_curves)
}

